name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Production
        uses: johnbeynon/render-deploy-action@v0.0.8
        environment: production
        with:
          api-key: ${{ secrets.RENDER_TOKEN }}
          service-id: srv-cjb5r6gcfp5c73be77cg

  monitor:
    name: Monitor Deployment

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Monitor Render Deployment
        uses: bounceapp/render-action@0.6.0
        with:
          render-token: ${{ secrets.RENDER_TOKEN }}
          github-token: ${{ secrets.REPO_TOKEN }}
          service-id: srv-cjb5r6gcfp5c73be77cg
          retries: 20
          wait: 16000
          sleep: 30000
