name: Render

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Wait for Deploy

    runs-on: ubuntu-latest

    steps:
      - name: Wait for Render Deployment
        uses: bounceapp/render-action@0.6.0
        with:
          render-token: ${{ secrets.RENDER_TOKEN }}
          github-token: ${{ secrets.REPO_TOKEN }}
          service-id: srv-cjb5r6gcfp5c73be77cg
          retries: 20
          wait: 16000
          sleep: 30000
